name: Testing env
on:
  workflow_dispatch:

jobs:
  read-infra-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read yaml
        id: read-yaml
        run: |
          echo 'Hello'

