# This is a basic workflow to help you get started with Actions

name: Testing env

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  read-infra-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        id: read-yaml
        run: |
#          debug
          echo "::debug::Set the Octocat variable"
          echo -n '::set-output name=data::'
          source .env
          echo $CR_REGISTRY
